# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16wDI5A3zd7ZOuXIRJcBbTAdUmYHv6dSL
"""

import pandas as pd
import streamlit as st

# Load data from Excel
df = pd.read_excel('your_excel_file.xlsx')

# Clean and trim the 'Title' column
df['Title'] = df['Title'].str.strip()

# Add leading zeros to make Product UPC 14 digits
df['Product UPC'] = df['Product UPC'].apply(lambda x: '{:.0f}'.format(x).zfill(14))

# Group by 'Title' and concatenate UPC codes
new_df = df.groupby('Title')['Product UPC'].apply(lambda x: ','.join(x)).reset_index()

# Streamlit app
st.title('UPC Concatenation App')
st.dataframe(new_df)